memory: 500M
db_password: mysecretpassword
db_user: ledger
db_name: ledger
db_ssl_option: ssl=none
disk_quota: 500M
disable_internal_https: 'true'
run_migration: 'true'
aws_access_key: x
aws_secret_key: x


